<?php

return [
    'menu' => [
        [
            'label' => 'Dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'order' => 10,
            'children' => [
                [
                    'label' => 'Executive Dashboard',
                    'route' => 'dashboard.index',
                    'icon' => 'fas fa-chart-line',
                    'nav_key' => 'dashboard_executive',
                ],
                [
                    'label' => 'Operations Financial Snapshot',
                    'route' => 'dashboard.index',
                    'icon' => 'fas fa-project-diagram',
                    'nav_key' => 'dashboard_operations',
                ],
            ],
        ],
        [
            'label' => 'Core Accounting',
            'icon' => 'fas fa-balance-scale',
            'order' => 20,
            'permission' => 'core-accounting.view',
            'children' => [
                [
                    'label' => 'Core Accounting Dashboard',
                    'route' => 'core-accounting.index',
                    'icon' => 'fas fa-home',
                    'nav_key' => 'core_dashboard',
                ],
                [
                    'label' => 'Chart of Accounts',
                    'route' => 'core-accounting.accounts.index',
                    'icon' => 'fas fa-sitemap',
                    'nav_key' => 'core_chart_of_accounts',
                ],
                [
                    'label' => 'Journal Management',
                    'route' => 'core-accounting.journals.index',
                    'icon' => 'fas fa-book-open',
                    'nav_key' => 'core_journal_management',
                ],
                [
                    'label' => 'Posting Sources',
                    'route' => 'core-accounting.posting-sources.index',
                    'icon' => 'fas fa-stream',
                    'nav_key' => 'core_posting_sources',
                ],
                [
                    'label' => 'Period Management',
                    'route' => 'core-accounting.periods.index',
                    'icon' => 'fas fa-calendar-alt',
                    'nav_key' => 'core_period_management',
                ],
                [
                    'label' => 'Posting Rules',
                    'route' => 'core-accounting.posting-rules.index',
                    'icon' => 'fas fa-random',
                    'nav_key' => 'core_posting_rules',
                ],
            ],
        ],
        [
            'label' => 'Accounts Receivable',
            'icon' => 'fas fa-file-invoice-dollar',
            'order' => 30,
            'permission' => 'accounts-receivable.view',
            'children' => [
                [
                    'label' => 'AR Dashboard',
                    'route' => 'accounts-receivable.index',
                    'icon' => 'fas fa-tachometer-alt',
                    'nav_key' => 'ar_dashboard',
                ],
                [
                    'label' => 'Invoices',
                    'route' => 'accounts-receivable.invoices.index',
                    'icon' => 'fas fa-file-invoice',
                    'nav_key' => 'ar_invoices',
                ],
                [
                    'label' => 'Statement of Account',
                    'route' => 'accounts-receivable.statement',
                    'icon' => 'fas fa-list-alt',
                    'nav_key' => 'ar_statement',
                ],
                [
                    'label' => 'AR Aging',
                    'route' => 'accounts-receivable.aging',
                    'icon' => 'fas fa-clock',
                    'nav_key' => 'ar_aging',
                ],
                [
                    'label' => 'Payments & Collections',
                    'route' => 'accounts-receivable.payments.index',
                    'icon' => 'fas fa-hand-holding-usd',
                    'nav_key' => 'ar_payments',
                ],
                [
                    'label' => 'Billing Engine',
                    'route' => 'billing-engine.index',
                    'icon' => 'fas fa-cash-register',
                    'permission' => 'billing-engine.view',
                    'nav_key' => 'ar_billing_engine',
                ],
            ],
        ],
        [
            'label' => 'Accounts Payable',
            'icon' => 'fas fa-file-invoice',
            'order' => 40,
            'permission' => 'accounts-payable.view',
            'children' => [
                [
                    'label' => 'AP Dashboard',
                    'route' => 'accounts-payable.index',
                    'icon' => 'fas fa-tachometer-alt',
                    'nav_key' => 'ap_dashboard',
                ],
                [
                    'label' => 'Vendors',
                    'route' => 'accounts-payable.vendors.index',
                    'icon' => 'fas fa-truck-loading',
                    'nav_key' => 'ap_vendors',
                ],
                [
                    'label' => 'Vendor Bills',
                    'route' => 'accounts-payable.bills.index',
                    'icon' => 'fas fa-file-invoice',
                    'nav_key' => 'ap_bills',
                ],
                [
                    'label' => 'Statement of Account',
                    'route' => 'accounts-payable.statement',
                    'icon' => 'fas fa-list-alt',
                    'nav_key' => 'ap_statement',
                ],
                [
                    'label' => 'AP Aging',
                    'route' => 'accounts-payable.aging',
                    'icon' => 'fas fa-clock',
                    'nav_key' => 'ap_aging',
                ],
                [
                    'label' => 'Payments',
                    'route' => 'accounts-payable.payments.index',
                    'icon' => 'fas fa-money-check-alt',
                    'nav_key' => 'ap_payments',
                ],
                [
                    'label' => 'Vouchers',
                    'route' => 'accounts-payable.vouchers.index',
                    'icon' => 'fas fa-receipt',
                    'nav_key' => 'ap_vouchers',
                ],
                [
                    'label' => 'Check register',
                    'route' => 'accounts-payable.checks.index',
                    'icon' => 'fas fa-money-check',
                    'nav_key' => 'ap_checks',
                ],
            ],
        ],
        [
            'label' => 'Costing & Profitability',
            'icon' => 'fas fa-balance-scale-right',
            'order' => 50,
            'permission' => 'costing-engine.view',
            'children' => [
                [
                    'label' => 'Shipment Profitability',
                    'route' => 'costing-engine.shipment-profitability',
                    'icon' => 'fas fa-boxes',
                    'nav_key' => 'costing_shipment',
                ],
                [
                    'label' => 'Client Profitability',
                    'route' => 'costing-engine.client-profitability',
                    'icon' => 'fas fa-user-tie',
                    'nav_key' => 'costing_client',
                ],
                [
                    'label' => 'Route Profitability',
                    'route' => 'costing-engine.route-profitability',
                    'icon' => 'fas fa-route',
                    'nav_key' => 'costing_route',
                ],
                [
                    'label' => 'Warehouse Profitability',
                    'route' => 'costing-engine.warehouse-profitability',
                    'icon' => 'fas fa-warehouse',
                    'nav_key' => 'costing_warehouse',
                ],
                [
                    'label' => 'Project Profitability',
                    'route' => 'costing-engine.project-profitability',
                    'icon' => 'fas fa-project-diagram',
                    'nav_key' => 'costing_project',
                ],
                [
                    'label' => 'Allocation Engine',
                    'route' => 'costing-engine.allocation-engine',
                    'icon' => 'fas fa-sliders-h',
                    'nav_key' => 'costing_allocation',
                ],
            ],
        ],
        [
            'label' => 'Inventory Control',
            'icon' => 'fas fa-box-open',
            'order' => 60,
            'permission' => 'inventory-valuation.view',
            'children' => [
                [
                    'label' => 'Own Inventory',
                    'route' => 'inventory-valuation.index',
                    'icon' => 'fas fa-layer-group',
                    'nav_key' => 'inventory_valuation',
                ],
                [
                    'label' => 'Valuation Report',
                    'route' => 'inventory-valuation.valuation',
                    'icon' => 'fas fa-calculator',
                    'nav_key' => 'inventory_valuation_report',
                ],
                [
                    'label' => 'Stock Movements',
                    'route' => 'inventory-valuation.movements.index',
                    'icon' => 'fas fa-exchange-alt',
                    'nav_key' => 'inventory_movements',
                ],
                [
                    'label' => 'Write-Off & Adjustments',
                    'route' => 'inventory-valuation.adjustments.index',
                    'icon' => 'fas fa-adjust',
                    'nav_key' => 'inventory_adjustments',
                ],
                [
                    'label' => 'Warehouses',
                    'route' => 'inventory-valuation.warehouses.index',
                    'icon' => 'fas fa-warehouse',
                    'nav_key' => 'inventory_warehouses',
                ],
                [
                    'label' => 'Items',
                    'route' => 'inventory-valuation.items.index',
                    'icon' => 'fas fa-boxes',
                    'nav_key' => 'inventory_items',
                ],
            ],
        ],
        [
            'label' => 'Fixed Assets',
            'icon' => 'fas fa-truck-moving',
            'order' => 70,
            'permission' => 'fixed-assets.view',
            'children' => [
                [
                    'label' => 'Asset Registry',
                    'route' => 'fixed-assets.assets.index',
                    'icon' => 'fas fa-clipboard-list',
                    'nav_key' => 'fa_registry',
                ],
                [
                    'label' => 'Depreciation',
                    'route' => 'fixed-assets.depreciation.index',
                    'icon' => 'fas fa-hourglass-half',
                    'nav_key' => 'fa_depreciation',
                ],
                [
                    'label' => 'Depreciation schedule',
                    'route' => 'fixed-assets.depreciation.schedule',
                    'icon' => 'fas fa-calendar-alt',
                    'nav_key' => 'fa_depreciation_schedule',
                ],
                [
                    'label' => 'Depreciation history',
                    'route' => 'fixed-assets.depreciation.history',
                    'icon' => 'fas fa-history',
                    'nav_key' => 'fa_depreciation_history',
                ],
                [
                    'label' => 'Maintenance Cost Tracking',
                    'route' => 'fixed-assets.maintenance.index',
                    'icon' => 'fas fa-tools',
                    'nav_key' => 'fa_maintenance',
                ],
                [
                    'label' => 'Reports',
                    'route' => 'fixed-assets.reports.index',
                    'icon' => 'fas fa-chart-bar',
                    'nav_key' => 'fa_reports',
                ],
            ],
        ],
        [
            'label' => 'Treasury & Cash',
            'icon' => 'fas fa-piggy-bank',
            'order' => 80,
            'permission' => 'treasury.view',
            'children' => [
                [
                    'label' => 'Treasury Dashboard',
                    'route' => 'treasury.index',
                    'icon' => 'fas fa-tachometer-alt',
                    'nav_key' => 'treasury_dashboard',
                ],
                [
                    'label' => 'Bank Accounts',
                    'route' => 'treasury.bank-accounts.index',
                    'icon' => 'fas fa-university',
                    'nav_key' => 'treasury_accounts',
                ],
                [
                    'label' => 'Bank Reconciliation',
                    'route' => 'treasury.reconciliation.index',
                    'icon' => 'fas fa-balance-scale',
                    'nav_key' => 'treasury_reconciliation',
                ],
                [
                    'label' => 'Cash Management',
                    'route' => 'treasury.index',
                    'icon' => 'fas fa-wallet',
                    'nav_key' => 'treasury_cash',
                ],
            ],
        ],
        [
            'label' => 'Financial Reports',
            'icon' => 'fas fa-chart-pie',
            'order' => 90,
            'children' => [
                [
                    'label' => 'General Reports',
                    'route' => 'general-ledger.index',
                    'icon' => 'fas fa-book',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_general',
                ],
                [
                    'label' => 'Trial Balance',
                    'route' => 'general-ledger.trial-balance',
                    'icon' => 'fas fa-balance-scale',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_trial_balance',
                ],
                [
                    'label' => 'General Ledger',
                    'route' => 'general-ledger.ledger',
                    'icon' => 'fas fa-book-open',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_general_ledger',
                ],
                [
                    'label' => 'Income Statement',
                    'route' => 'general-ledger.income-statement',
                    'icon' => 'fas fa-file-invoice-dollar',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_income_statement',
                ],
                [
                    'label' => 'Balance Sheet',
                    'route' => 'general-ledger.balance-sheet',
                    'icon' => 'fas fa-balance-scale-right',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_balance_sheet',
                ],
                [
                    'label' => 'Cash Flow',
                    'route' => 'general-ledger.cash-flow',
                    'icon' => 'fas fa-money-bill-wave',
                    'permission' => 'general-ledger.view',
                    'nav_key' => 'reports_cash_flow',
                ],
                [
                    'label' => 'Management Reports',
                    'route' => 'financial-reporting.management-reports',
                    'icon' => 'fas fa-chart-line',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_management',
                ],
                [
                    'label' => 'Comparative Income Statement',
                    'route' => 'financial-reporting.comparative-income-statement',
                    'icon' => 'fas fa-columns',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_comparative',
                ],
                [
                    'label' => 'Tax Summary',
                    'route' => 'financial-reporting.tax-summary',
                    'icon' => 'fas fa-receipt',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_tax_summary',
                ],
                [
                    'label' => 'Management P&L by dimension',
                    'route' => 'financial-reporting.management-pl-dimension',
                    'icon' => 'fas fa-layer-group',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_pl_dimension',
                ],
                [
                    'label' => 'P&L per Revenue',
                    'route' => 'financial-reporting.pl-per-revenue',
                    'icon' => 'fas fa-chart-pie',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_pl_per_revenue',
                ],
                [
                    'label' => 'Cash flow analysis',
                    'route' => 'financial-reporting.cash-flow-analysis',
                    'icon' => 'fas fa-money-bill-wave',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_cash_flow_analysis',
                ],
                [
                    'label' => 'AR/AP KPI dashboard',
                    'route' => 'financial-reporting.kpi-dashboard',
                    'icon' => 'fas fa-tachometer-alt',
                    'permission' => 'financial-reporting.view',
                    'nav_key' => 'reports_kpi_dashboard',
                ],
            ],
        ],
        [
            'label' => 'Integration Center',
            'icon' => 'fas fa-plug',
            'order' => 100,
            'permission' => 'lfs-administration.view',
            'children' => [
                [
                    'label' => 'Financial Events Monitor',
                    'route' => 'lfs-administration.integration-events',
                    'icon' => 'fas fa-stream',
                    'nav_key' => 'integration_events',
                ],
                [
                    'label' => 'Sync Logs',
                    'route' => 'lfs-administration.sync-logs',
                    'icon' => 'fas fa-clipboard-list',
                    'nav_key' => 'integration_sync_logs',
                ],
            ],
        ],
        [
            'label' => 'Approval Workflows',
            'icon' => 'fas fa-check-circle',
            'order' => 110,
            'permission' => 'lfs-administration.view',
            'children' => [
                [
                    'label' => 'Journal Approval',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-book-reader',
                    'nav_key' => 'workflow_journal',
                ],
                [
                    'label' => 'Invoice Approval',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-file-invoice-dollar',
                    'nav_key' => 'workflow_invoice',
                ],
                [
                    'label' => 'Vendor Bill Approval',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-file-invoice',
                    'nav_key' => 'workflow_vendor_bill',
                ],
                [
                    'label' => 'Allocation Approval',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-sliders-h',
                    'nav_key' => 'workflow_allocation',
                ],
                [
                    'label' => 'Credit Note Approval',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-file-invoice',
                    'nav_key' => 'workflow_credit_note',
                ],
            ],
        ],
        [
            'label' => 'Audit & Governance',
            'icon' => 'fas fa-user-shield',
            'order' => 120,
            'permission' => 'lfs-administration.view',
            'children' => [
                [
                    'label' => 'Audit Logs',
                    'route' => 'lfs-administration.audit-logs',
                    'icon' => 'fas fa-clipboard-check',
                    'nav_key' => 'governance_audit_logs',
                ],
                [
                    'label' => 'Role & Permission Management',
                    'route' => 'lfs-administration.roles',
                    'icon' => 'fas fa-users-cog',
                    'nav_key' => 'governance_roles',
                ],
            ],
        ],
        [
            'label' => 'System Settings',
            'icon' => 'fas fa-cogs',
            'order' => 130,
            'permission' => 'lfs-administration.view',
            'children' => [
                [
                    'label' => 'Company Settings',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-building',
                    'nav_key' => 'settings_company',
                ],
                [
                    'label' => 'Financial Controls',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-lock',
                    'nav_key' => 'settings_financial_controls',
                ],
                [
                    'label' => 'Tax Configuration',
                    'route' => 'lfs-administration.index',
                    'icon' => 'fas fa-percentage',
                    'nav_key' => 'settings_tax',
                ],
            ],
        ],
    ],
];

